version: '3'
services:
  admin_panel:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    # env_file:
    #   - ./.env
    ports:
      - '3000:3000'
